"use client";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "src/components/navbar";

// Load Inter font using next/font for optimization
const inter = Inter({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          headerSubtitle: "text-gray-900",
          headerTitle: "text-gray-900",
          dividerText: "text-gray-900",
          card: "bg-white shadow-lg",
          formButtonPrimary:
            "bg-green-700 hover:bg-green-800 text-white font-semibold",
        },
        variables: {
          colorText: "#111827",
          colorPrimary: "#047857",
        },
      }}
    >
      <html lang="en">
        <head>
          {/* No need to manually preload or link the font if you're using next/font */}
        </head>
        <body className={inter.className}>
          <Navbar />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
